[package]
name = "chaos-chat-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
tokio-tungstenite = "0.21"
tungstenite = "0.21"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = "0.3"
dashmap = "5.5"
atomic_counter = "1.0"
once_cell = "1.19"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
